<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ResetYourFuture.Domain\ResetYourFuture.Domain.csproj" />
    <ProjectReference Include="..\..\src\ResetYourFuture.Application\ResetYourFuture.Application.csproj" />
    <ProjectReference Include="..\..\src\ResetYourFuture.Infrastructure\ResetYourFuture.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\ResetYourFuture.Shared\ResetYourFuture.Shared.csproj" />
    <ProjectReference Include="..\..\src\ResetYourFuture.Web\ResetYourFuture.Web.csproj" />
    <ProjectReference Include="..\ResetYourFuture.TestSupport\ResetYourFuture.TestSupport.csproj" />
  </ItemGroup>

</Project>
