//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResetYourFuture.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AssessmentRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AssessmentRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResetYourFuture.Shared.Resources.AssessmentRes", typeof(AssessmentRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading...
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Assessment Submitted Successfully!
        /// </summary>
        public static string SubmittedTitle {
            get {
                return ResourceManager.GetString("SubmittedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Thank you for completing the assessment.
        /// </summary>
        public static string SubmittedMessage {
            get {
                return ResourceManager.GetString("SubmittedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View My Submissions.
        /// </summary>
        public static string ViewSubmissions {
            get {
                return ResourceManager.GetString("ViewSubmissions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to -- Select --.
        /// </summary>
        public static string SelectPlaceholder {
            get {
                return ResourceManager.GetString("SelectPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Submit Assessment.
        /// </summary>
        public static string SubmitAssessment {
            get {
                return ResourceManager.GetString("SubmitAssessment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to My Assessment Submissions.
        /// </summary>
        public static string HistoryTitle {
            get {
                return ResourceManager.GetString("HistoryTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You haven't submitted any assessments yet.
        /// </summary>
        public static string NoSubmissionsMessage {
            get {
                return ResourceManager.GetString("NoSubmissionsMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Take an Assessment.
        /// </summary>
        public static string TakeAssessment {
            get {
                return ResourceManager.GetString("TakeAssessment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Latest Submission.
        /// </summary>
        public static string LatestSubmission {
            get {
                return ResourceManager.GetString("LatestSubmission", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Submitted:.
        /// </summary>
        public static string SubmittedLabel {
            get {
                return ResourceManager.GetString("SubmittedLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All Submissions.
        /// </summary>
        public static string AllSubmissions {
            get {
                return ResourceManager.GetString("AllSubmissions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Assessment.
        /// </summary>
        public static string AssessmentHeader {
            get {
                return ResourceManager.GetString("AssessmentHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        public static string SubmittedHeader {
            get {
                return ResourceManager.GetString("SubmittedHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ViewButton {
            get {
                return ResourceManager.GetString("ViewButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your Answers:.
        /// </summary>
        public static string YourAnswers {
            get {
                return ResourceManager.GetString("YourAnswers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Summary:.
        /// </summary>
        public static string SummaryLabel {
            get {
                return ResourceManager.GetString("SummaryLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
    }
}
