//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResetYourFuture.Shared.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CategoryRes {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CategoryRes() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResetYourFuture.Shared.Resources.CategoryRes", typeof(CategoryRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string CategoriesPageTitle {
            get {
                return ResourceManager.GetString("CategoriesPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name (EN).
        /// </summary>
        public static string ColNameEn {
            get {
                return ResourceManager.GetString("ColNameEn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name (EL).
        /// </summary>
        public static string ColNameEl {
            get {
                return ResourceManager.GetString("ColNameEl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string ColCourseCount {
            get {
                return ResourceManager.GetString("ColCourseCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Assessments.
        /// </summary>
        public static string ColAssessmentCount {
            get {
                return ResourceManager.GetString("ColAssessmentCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string ColCreated {
            get {
                return ResourceManager.GetString("ColCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string ColActions {
            get {
                return ResourceManager.GetString("ColActions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete '{0}'? {1} course(s) and {2} assessment(s) will become uncategorized..
        /// </summary>
        public static string DeleteConfirmFormat {
            get {
                return ResourceManager.GetString("DeleteConfirmFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No categories yet..
        /// </summary>
        public static string NoCategories {
            get {
                return ResourceManager.GetString("NoCategories", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading categories....
        /// </summary>
        public static string LoadingCategories {
            get {
                return ResourceManager.GetString("LoadingCategories", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name (English).
        /// </summary>
        public static string NameEnLabel {
            get {
                return ResourceManager.GetString("NameEnLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name (Greek).
        /// </summary>
        public static string NameElLabel {
            get {
                return ResourceManager.GetString("NameElLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string AllCategories {
            get {
                return ResourceManager.GetString("AllCategories", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No results match your filters..
        /// </summary>
        public static string NoMatchingResults {
            get {
                return ResourceManager.GetString("NoMatchingResults", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to — None —.
        /// </summary>
        public static string NoneCategory {
            get {
                return ResourceManager.GetString("NoneCategory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to + New category….
        /// </summary>
        public static string NewCategoryOption {
            get {
                return ResourceManager.GetString("NewCategoryOption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New category name.
        /// </summary>
        public static string NewCategoryNamePlaceholder {
            get {
                return ResourceManager.GetString("NewCategoryNamePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CategoryLabel {
            get {
                return ResourceManager.GetString("CategoryLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Category saved.
        /// </summary>
        public static string CategorySaved {
            get {
                return ResourceManager.GetString("CategorySaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Category deleted.
        /// </summary>
        public static string CategoryDeleted {
            get {
                return ResourceManager.GetString("CategoryDeleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error saving category.
        /// </summary>
        public static string ErrorSavingCategory {
            get {
                return ResourceManager.GetString("ErrorSavingCategory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error deleting category.
        /// </summary>
        public static string ErrorDeletingCategory {
            get {
                return ResourceManager.GetString("ErrorDeletingCategory", resourceCulture);
            }
        }
    }
}
