//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResetYourFuture.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CourseRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CourseRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResetYourFuture.Shared.Resources.CourseRes", typeof(CourseRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string CourseDefault {
            get {
                return ResourceManager.GetString("CourseDefault", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading course...
        /// </summary>
        public static string LoadingCourse {
            get {
                return ResourceManager.GetString("LoadingCourse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ← Back to Courses.
        /// </summary>
        public static string BackToCourses {
            get {
                return ResourceManager.GetString("BackToCourses", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Course not found.
        /// </summary>
        public static string CourseNotFound {
            get {
                return ResourceManager.GetString("CourseNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} / {1} lessons completed ({2}%).
        /// </summary>
        public static string ProgressFormat {
            get {
                return ResourceManager.GetString("ProgressFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 🎉 Course Completed!
        /// </summary>
        public static string CourseCompleted {
            get {
                return ResourceManager.GetString("CourseCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enrolling...
        /// </summary>
        public static string Enrolling {
            get {
                return ResourceManager.GetString("Enrolling", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enroll in This Course.
        /// </summary>
        public static string EnrollInThisCourse {
            get {
                return ResourceManager.GetString("EnrollInThisCourse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string MinutesShort {
            get {
                return ResourceManager.GetString("MinutesShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Courses - Reset Your Future.
        /// </summary>
        public static string CoursesPageTitle {
            get {
                return ResourceManager.GetString("CoursesPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Available Courses.
        /// </summary>
        public static string AvailableCourses {
            get {
                return ResourceManager.GetString("AvailableCourses", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading courses...
        /// </summary>
        public static string LoadingCourses {
            get {
                return ResourceManager.GetString("LoadingCourses", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No courses available at the moment.
        /// </summary>
        public static string NoCoursesAvailable {
            get {
                return ResourceManager.GetString("NoCoursesAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} lessons.
        /// </summary>
        public static string LessonsCountFormat {
            get {
                return ResourceManager.GetString("LessonsCountFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ✓ Enrolled.
        /// </summary>
        public static string Enrolled {
            get {
                return ResourceManager.GetString("Enrolled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 🔒 Upgrade to {0}.
        /// </summary>
        public static string UpgradeToFormat {
            get {
                return ResourceManager.GetString("UpgradeToFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} courses.
        /// </summary>
        public static string TotalCoursesFormat {
            get {
                return ResourceManager.GetString("TotalCoursesFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Per page:.
        /// </summary>
        public static string PerPage {
            get {
                return ResourceManager.GetString("PerPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This course requires the {0} plan or higher.
        /// </summary>
        public static string RequiresPlanFormat {
            get {
                return ResourceManager.GetString("RequiresPlanFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Upgrade Plan.
        /// </summary>
        public static string UpgradePlan {
            get {
                return ResourceManager.GetString("UpgradePlan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You are on the {0} plan — up to {1} course(s).
        /// </summary>
        public static string PlanCourseLimitFormat {
            get {
                return ResourceManager.GetString("PlanCourseLimitFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You have used all your course slots.
        /// </summary>
        public static string CourseSlotsFullNotice {
            get {
                return ResourceManager.GetString("CourseSlotsFullNotice", resourceCulture);
            }
        }
    }
}
