//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResetYourFuture.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResetYourFuture.Shared.Resources.GlobalRes", typeof(GlobalRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address and we&apos;ll send you a password reset link..
        /// </summary>
        public static string ForgotPasswordInstructions {
            get {
                return ResourceManager.GetString("ForgotPasswordInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgotPasswordTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string Label_AlreadyHaveAccount {
            get {
                return ResourceManager.GetString("Label_AlreadyHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        public static string Label_ConfirmEmail {
            get {
                return ResourceManager.GetString("Label_ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Label_ConfirmPassword {
            get {
                return ResourceManager.GetString("Label_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string Label_CreateAccount {
            get {
                return ResourceManager.GetString("Label_CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev Mode:.
        /// </summary>
        public static string Label_DevMode {
            get {
                return ResourceManager.GetString("Label_DevMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev: Reset Password.
        /// </summary>
        public static string Label_DevResetPassword {
            get {
                return ResourceManager.GetString("Label_DevResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string Label_ForgotPassword {
            get {
                return ResourceManager.GetString("Label_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I consent to the processing of my personal data (required)..
        /// </summary>
        public static string Label_GdprConsent {
            get {
                return ResourceManager.GetString("Label_GdprConsent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to By registering, you agree to our.
        /// </summary>
        public static string ConsentPolicyIntro {
            get {
                return ResourceManager.GetString("ConsentPolicyIntro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to and our.
        /// </summary>
        public static string ConsentPolicyAnd {
            get {
                return ResourceManager.GetString("ConsentPolicyAnd", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string Label_Info_DateOfBirth {
            get {
                return ResourceManager.GetString("Label_Info_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Label_Info_Email {
            get {
                return ResourceManager.GetString("Label_Info_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Label_Info_FirstName {
            get {
                return ResourceManager.GetString("Label_Info_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Label_Info_LastName {
            get {
                return ResourceManager.GetString("Label_Info_LastName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Label_Info_Status {
            get {
                return ResourceManager.GetString("Label_Info_Status", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logging In....
        /// </summary>
        public static string Label_LoggingIn {
            get {
                return ResourceManager.GetString("Label_LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Label_Login {
            get {
                return ResourceManager.GetString("Label_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 8 characters.
        /// </summary>
        public static string Label_Minimum8Chars {
            get {
                return ResourceManager.GetString("Label_Minimum8Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string Label_NewPassword {
            get {
                return ResourceManager.GetString("Label_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string Label_NoAccount {
            get {
                return ResourceManager.GetString("Label_NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Label_Register {
            get {
                return ResourceManager.GetString("Label_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering....
        /// </summary>
        public static string Label_Registering {
            get {
                return ResourceManager.GetString("Label_Registering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string Label_RememberMe {
            get {
                return ResourceManager.GetString("Label_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending....
        /// </summary>
        public static string Label_Sending {
            get {
                return ResourceManager.GetString("Label_Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Reset Link.
        /// </summary>
        public static string Label_SendResetLink {
            get {
                return ResourceManager.GetString("Label_SendResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to view this page..
        /// </summary>
        public static string NotAuthorizedMessage {
            get {
                return ResourceManager.GetString("NotAuthorizedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You don't have access to this area..
        /// </summary>
        public static string NotAuthorizedRoleMessage {
            get {
                return ResourceManager.GetString("NotAuthorizedRoleMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to At least 8 characters, including a number and an uppercase letter..
        /// </summary>
        public static string PasswordRulesHint {
            get {
                return ResourceManager.GetString("PasswordRulesHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Newer.
        /// </summary>
        public static string PaginationNewer {
            get {
                return ResourceManager.GetString("PaginationNewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string PaginationNext {
            get {
                return ResourceManager.GetString("PaginationNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Older.
        /// </summary>
        public static string PaginationOlder {
            get {
                return ResourceManager.GetString("PaginationOlder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        public static string PaginationPageOfFormat {
            get {
                return ResourceManager.GetString("PaginationPageOfFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string PaginationPrev {
            get {
                return ResourceManager.GetString("PaginationPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows:.
        /// </summary>
        public static string PaginationRows {
            get {
                return ResourceManager.GetString("PaginationRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing {0}–{1} of {2} {3}.
        /// </summary>
        public static string PaginationShowingFormat {
            get {
                return ResourceManager.GetString("PaginationShowingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or hide password.
        /// </summary>
        public static string ShowHidePassword {
            get {
                return ResourceManager.GetString("ShowHidePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to main content.
        /// </summary>
        public static string SkipToContent {
            get {
                return ResourceManager.GetString("SkipToContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string PresenceOnline {
            get {
                return ResourceManager.GetString("PresenceOnline", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string PresenceOffline {
            get {
                return ResourceManager.GetString("PresenceOffline", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to last seen just now.
        /// </summary>
        public static string LastSeenJustNow {
            get {
                return ResourceManager.GetString("LastSeenJustNow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to last seen {0} min ago.
        /// </summary>
        public static string LastSeenMinutesFormat {
            get {
                return ResourceManager.GetString("LastSeenMinutesFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to last seen {0} h ago.
        /// </summary>
        public static string LastSeenHoursFormat {
            get {
                return ResourceManager.GetString("LastSeenHoursFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to last seen {0} d ago.
        /// </summary>
        public static string LastSeenDaysFormat {
            get {
                return ResourceManager.GetString("LastSeenDaysFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to last seen {0}.
        /// </summary>
        public static string LastSeenDateFormat {
            get {
                return ResourceManager.GetString("LastSeenDateFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Page not found.
        /// </summary>
        public static string NotFoundTitle {
            get {
                return ResourceManager.GetString("NotFoundTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The page you&apos;re looking for doesn&apos;t exist, was moved, or the link may be out of date..
        /// </summary>
        public static string NotFoundMessage {
            get {
                return ResourceManager.GetString("NotFoundMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Back to home.
        /// </summary>
        public static string BackToHome {
            get {
                return ResourceManager.GetString("BackToHome", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unsaved Changes.
        /// </summary>
        public static string UnsavedChangesTitle {
            get {
                return ResourceManager.GetString("UnsavedChangesTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes. Are you sure you want to leave this page?.
        /// </summary>
        public static string UnsavedChangesMessage {
            get {
                return ResourceManager.GetString("UnsavedChangesMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Discard Changes.
        /// </summary>
        public static string DiscardChanges {
            get {
                return ResourceManager.GetString("DiscardChanges", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Keep Editing.
        /// </summary>
        public static string KeepEditing {
            get {
                return ResourceManager.GetString("KeepEditing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page navigation.
        /// </summary>
        public static string PageNavigation {
            get {
                return ResourceManager.GetString("PageNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingEllipsis {
            get {
                return ResourceManager.GetString("LoadingEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items found..
        /// </summary>
        public static string NoItemsFound {
            get {
                return ResourceManager.GetString("NoItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string StatusPublished {
            get {
                return ResourceManager.GetString("StatusPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string StatusDraft {
            get {
                return ResourceManager.GetString("StatusDraft", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string StatusStudent {
            get {
                return ResourceManager.GetString("StatusStudent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Graduate.
        /// </summary>
        public static string StatusGraduate {
            get {
                return ResourceManager.GetString("StatusGraduate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NEET (not in education, employment, or training).
        /// </summary>
        public static string StatusNEET {
            get {
                return ResourceManager.GetString("StatusNEET", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string StatusOther {
            get {
                return ResourceManager.GetString("StatusOther", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Navigation menu.
        /// </summary>
        public static string NavigationMenu {
            get {
                return ResourceManager.GetString("NavigationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled error has occurred..
        /// </summary>
        public static string UnhandledError {
            get {
                return ResourceManager.GetString("UnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this feature.
        /// </summary>
        public static string ThisFeature {
            get {
                return ResourceManager.GetString("ThisFeature", resourceCulture);
            }
        }
        
    }
}
