//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResetYourFuture.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResetYourFuture.Shared.Resources.HomeRes", typeof(HomeRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged in. Visit your &lt;a href=&quot;/profile&quot;&gt;profile&lt;/a&gt; to see your details..
        /// </summary>
        public static string AuthenticatedMessage {
            get {
                return ResourceManager.GetString("AuthenticatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book a free session.
        /// </summary>
        public static string CtaButton {
            get {
                return ResourceManager.GetString("CtaButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book a free short diagnostic session and see if Reset Your Future is for you..
        /// </summary>
        public static string CtaText {
            get {
                return ResourceManager.GetString("CtaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The next step.
        /// </summary>
        public static string CtaTitle {
            get {
                return ResourceManager.GetString("CtaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starts here.
        /// </summary>
        public static string CtaTitleHighlight {
            get {
                return ResourceManager.GetString("CtaTitleHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgios Kokkalis.
        /// </summary>
        public static string FooterAuthorName {
            get {
                return ResourceManager.GetString("FooterAuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career Guidance Counselor.
        /// </summary>
        public static string FooterAuthorRole {
            get {
                return ResourceManager.GetString("FooterAuthorRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Your Future.
        /// </summary>
        public static string FooterBrand {
            get {
                return ResourceManager.GetString("FooterBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2026 Reset Your Future.
        /// </summary>
        public static string FooterCopyright {
            get {
                return ResourceManager.GetString("FooterCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book a free diagnostic session.
        /// </summary>
        public static string HeroCtaButton {
            get {
                return ResourceManager.GetString("HeroCtaButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-awareness.
        /// </summary>
        public static string HeroState1 {
            get {
                return ResourceManager.GetString("HeroState1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resilience.
        /// </summary>
        public static string HeroState2 {
            get {
                return ResourceManager.GetString("HeroState2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hope.
        /// </summary>
        public static string HeroState3 {
            get {
                return ResourceManager.GetString("HeroState3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidence.
        /// </summary>
        public static string HeroState4 {
            get {
                return ResourceManager.GetString("HeroState4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string HeroState5 {
            get {
                return ResourceManager.GetString("HeroState5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hero State.
        /// </summary>
        public static string HeroStateTitle {
            get {
                return ResourceManager.GetString("HeroStateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first Greek online platform that combines career guidance with psychosocial empowerment for high school students and graduates..
        /// </summary>
        public static string HeroSubtitle {
            get {
                return ResourceManager.GetString("HeroSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From frustration to clarity.
        /// </summary>
        public static string HeroTitleLine1 {
            get {
                return ResourceManager.GetString("HeroTitleLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Zero to Hero.
        /// </summary>
        public static string HeroTitleLine2 {
            get {
                return ResourceManager.GetString("HeroTitleLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From the.
        /// </summary>
        public static string MethodTitleFrom {
            get {
                return ResourceManager.GetString("MethodTitleFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hero State.
        /// </summary>
        public static string MethodTitleHeroState {
            get {
                return ResourceManager.GetString("MethodTitleHeroState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to the.
        /// </summary>
        public static string MethodTitleTo {
            get {
                return ResourceManager.GetString("MethodTitleTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero State.
        /// </summary>
        public static string MethodTitleZeroState {
            get {
                return ResourceManager.GetString("MethodTitleZeroState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Your Future | Career Guidance.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t achieve the grades you expected.
        /// </summary>
        public static string ProblemCard1 {
            get {
                return ResourceManager.GetString("ProblemCard1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You feel lost without a clear direction.
        /// </summary>
        public static string ProblemCard2 {
            get {
                return ResourceManager.GetString("ProblemCard2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You feel pressure from parents and society.
        /// </summary>
        public static string ProblemCard3 {
            get {
                return ResourceManager.GetString("ProblemCard3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You doubt yourself and your abilities.
        /// </summary>
        public static string ProblemCard4 {
            get {
                return ResourceManager.GetString("ProblemCard4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not a failure..
        /// </summary>
        public static string ProblemConclusion {
            get {
                return ResourceManager.GetString("ProblemConclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No one taught you how to handle failure..
        /// </summary>
        public static string ProblemConclusionHighlight {
            get {
                return ResourceManager.GetString("ProblemConclusionHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this sounds familiar,.
        /// </summary>
        public static string ProblemTitle {
            get {
                return ResourceManager.GetString("ProblemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you&apos;re in the right place.
        /// </summary>
        public static string ProblemTitleHighlight {
            get {
                return ResourceManager.GetString("ProblemTitleHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structured courses on self-awareness, resilience, and decision-making..
        /// </summary>
        public static string SolutionCard1Text {
            get {
                return ResourceManager.GetString("SolutionCard1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Courses.
        /// </summary>
        public static string SolutionCard1Title {
            get {
                return ResourceManager.GetString("SolutionCard1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual and group support with a clear action plan..
        /// </summary>
        public static string SolutionCard2Text {
            get {
                return ResourceManager.GetString("SolutionCard2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counseling Sessions.
        /// </summary>
        public static string SolutionCard2Title {
            get {
                return ResourceManager.GetString("SolutionCard2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not alone. Learn and grow together with others..
        /// </summary>
        public static string SolutionCard3Text {
            get {
                return ResourceManager.GetString("SolutionCard3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Community.
        /// </summary>
        public static string SolutionCard3Title {
            get {
                return ResourceManager.GetString("SolutionCard3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is.
        /// </summary>
        public static string SolutionTitle {
            get {
                return ResourceManager.GetString("SolutionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Your Future.
        /// </summary>
        public static string SolutionTitleHighlight {
            get {
                return ResourceManager.GetString("SolutionTitleHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GK.
        /// </summary>
        public static string StoryAuthorInitials {
            get {
                return ResourceManager.GetString("StoryAuthorInitials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgios Kokkalis.
        /// </summary>
        public static string StoryAuthorName {
            get {
                return ResourceManager.GetString("StoryAuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founder.
        /// </summary>
        public static string StoryAuthorTitle {
            get {
                return ResourceManager.GetString("StoryAuthorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In 2014, I failed the national exams. I felt lost and without direction. Today, I help students turn failure into strength and an action plan..
        /// </summary>
        public static string StoryQuote {
            get {
                return ResourceManager.GetString("StoryQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The story behind.
        /// </summary>
        public static string StoryTitle {
            get {
                return ResourceManager.GetString("StoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Your Future.
        /// </summary>
        public static string StoryTitleHighlight {
            get {
                return ResourceManager.GetString("StoryTitleHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome, {0}!.
        /// </summary>
        public static string WelcomeUser {
            get {
                return ResourceManager.GetString("WelcomeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insecurity.
        /// </summary>
        public static string ZeroState1 {
            get {
                return ResourceManager.GetString("ZeroState1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confusion.
        /// </summary>
        public static string ZeroState2 {
            get {
                return ResourceManager.GetString("ZeroState2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fear of failure.
        /// </summary>
        public static string ZeroState3 {
            get {
                return ResourceManager.GetString("ZeroState3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social pressure.
        /// </summary>
        public static string ZeroState4 {
            get {
                return ResourceManager.GetString("ZeroState4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero State.
        /// </summary>
        public static string ZeroStateTitle {
            get {
                return ResourceManager.GetString("ZeroStateTitle", resourceCulture);
            }
        }
    }
}
