//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResetYourFuture.Shared.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LegalRes {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LegalRes() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResetYourFuture.Shared.Resources.LegalRes", typeof(LegalRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Last updated: July 2026.
        /// </summary>
        public static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Educational project.
        /// </summary>
        public static string EducationalNoticeTitle {
            get {
                return ResourceManager.GetString("EducationalNoticeTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset Your Future is a university certificate project. ....
        /// </summary>
        public static string EducationalNotice {
            get {
                return ResourceManager.GetString("EducationalNotice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyTitle {
            get {
                return ResourceManager.GetString("PrivacyTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset Your Future is an online career-counselling ....
        /// </summary>
        public static string PrivacyIntro {
            get {
                return ResourceManager.GetString("PrivacyIntro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to What data we collect.
        /// </summary>
        public static string PrivacyDataTitle {
            get {
                return ResourceManager.GetString("PrivacyDataTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to When you create an account we store your name, ....
        /// </summary>
        public static string PrivacyDataBody {
            get {
                return ResourceManager.GetString("PrivacyDataBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Why we process your data.
        /// </summary>
        public static string PrivacyPurposeTitle {
            get {
                return ResourceManager.GetString("PrivacyPurposeTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to We process your data to give you access ....
        /// </summary>
        public static string PrivacyPurposeBody {
            get {
                return ResourceManager.GetString("PrivacyPurposeBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Assessment (special-category) data.
        /// </summary>
        public static string PrivacySpecialTitle {
            get {
                return ResourceManager.GetString("PrivacySpecialTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Some assessments ask about your wellbeing, ....
        /// </summary>
        public static string PrivacySpecialBody {
            get {
                return ResourceManager.GetString("PrivacySpecialBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to How long we keep your data.
        /// </summary>
        public static string PrivacyRetentionTitle {
            get {
                return ResourceManager.GetString("PrivacyRetentionTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to We keep your account data for as long ....
        /// </summary>
        public static string PrivacyRetentionBody {
            get {
                return ResourceManager.GetString("PrivacyRetentionBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your rights.
        /// </summary>
        public static string PrivacyRightsTitle {
            get {
                return ResourceManager.GetString("PrivacyRightsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You have the right to access the personal data ....
        /// </summary>
        public static string PrivacyRightsBody {
            get {
                return ResourceManager.GetString("PrivacyRightsBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cookies.
        /// </summary>
        public static string PrivacyCookiesTitle {
            get {
                return ResourceManager.GetString("PrivacyCookiesTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to We use only essential cookies ....
        /// </summary>
        public static string PrivacyCookiesBody {
            get {
                return ResourceManager.GetString("PrivacyCookiesBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contact and changes.
        /// </summary>
        public static string PrivacyContactTitle {
            get {
                return ResourceManager.GetString("PrivacyContactTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to We may update this policy as the platform evolves ....
        /// </summary>
        public static string PrivacyContactBody {
            get {
                return ResourceManager.GetString("PrivacyContactBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        public static string TermsTitle {
            get {
                return ResourceManager.GetString("TermsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to These terms govern your use of Reset Your Future ....
        /// </summary>
        public static string TermsIntro {
            get {
                return ResourceManager.GetString("TermsIntro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The service.
        /// </summary>
        public static string TermsServiceTitle {
            get {
                return ResourceManager.GetString("TermsServiceTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset Your Future offers online courses ....
        /// </summary>
        public static string TermsServiceBody {
            get {
                return ResourceManager.GetString("TermsServiceBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your account.
        /// </summary>
        public static string TermsAccountsTitle {
            get {
                return ResourceManager.GetString("TermsAccountsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You are responsible for the accuracy ....
        /// </summary>
        public static string TermsAccountsBody {
            get {
                return ResourceManager.GetString("TermsAccountsBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Acceptable use.
        /// </summary>
        public static string TermsAcceptableTitle {
            get {
                return ResourceManager.GetString("TermsAcceptableTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You agree not to misuse the platform ....
        /// </summary>
        public static string TermsAcceptableBody {
            get {
                return ResourceManager.GetString("TermsAcceptableBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Content and intellectual property.
        /// </summary>
        public static string TermsContentTitle {
            get {
                return ResourceManager.GetString("TermsContentTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Course materials, text and branding ....
        /// </summary>
        public static string TermsContentBody {
            get {
                return ResourceManager.GetString("TermsContentBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Assessments and AI assistant.
        /// </summary>
        public static string TermsAssessmentsTitle {
            get {
                return ResourceManager.GetString("TermsAssessmentsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The assessments and the AI assistant provide ....
        /// </summary>
        public static string TermsAssessmentsBody {
            get {
                return ResourceManager.GetString("TermsAssessmentsBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disclaimers and liability.
        /// </summary>
        public static string TermsDisclaimerTitle {
            get {
                return ResourceManager.GetString("TermsDisclaimerTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The platform is provided "as is" ....
        /// </summary>
        public static string TermsDisclaimerBody {
            get {
                return ResourceManager.GetString("TermsDisclaimerBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Changes and contact.
        /// </summary>
        public static string TermsChangesTitle {
            get {
                return ResourceManager.GetString("TermsChangesTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to We may update these terms as the project develops ....
        /// </summary>
        public static string TermsChangesBody {
            get {
                return ResourceManager.GetString("TermsChangesBody", resourceCulture);
            }
        }
    }
}
