//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResetYourFuture.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LessonRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LessonRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResetYourFuture.Shared.Resources.LessonRes", typeof(LessonRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ← Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Course.
        /// </summary>
        public static string BackToCourse {
            get {
                return ResourceManager.GetString("BackToCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓ Completed.
        /// </summary>
        public static string CompletedIndicator {
            get {
                return ResourceManager.GetString("CompletedIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎉 Course Completed!.
        /// </summary>
        public static string CourseCompleted {
            get {
                return ResourceManager.GetString("CourseCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load lesson. Please try again..
        /// </summary>
        public static string FailedToLoadLesson {
            get {
                return ResourceManager.GetString("FailedToLoadLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson.
        /// </summary>
        public static string LessonDefault {
            get {
                return ResourceManager.GetString("LessonDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson not found..
        /// </summary>
        public static string LessonNotFound {
            get {
                return ResourceManager.GetString("LessonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson not found or you are not enrolled in this course..
        /// </summary>
        public static string LessonNotFoundOrNotEnrolled {
            get {
                return ResourceManager.GetString("LessonNotFoundOrNotEnrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading lesson....
        /// </summary>
        public static string LoadingLesson {
            get {
                return ResourceManager.GetString("LoadingLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓ Mark as Complete.
        /// </summary>
        public static string MarkAsComplete {
            get {
                return ResourceManager.GetString("MarkAsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Lesson →.
        /// </summary>
        public static string NextLesson {
            get {
                return ResourceManager.GetString("NextLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ← Previous Lesson.
        /// </summary>
        public static string PreviousLesson {
            get {
                return ResourceManager.GetString("PreviousLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress: {0} / {1} ({2}%).
        /// </summary>
        public static string ProgressFormat {
            get {
                return ResourceManager.GetString("ProgressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
    }
}
