//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResetYourFuture.Shared.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationRes {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationRes() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResetYourFuture.Shared.Resources.NotificationRes", typeof(NotificationRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string OpenNotifications {
            get {
                return ResourceManager.GetString("OpenNotifications", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} unread notifications.
        /// </summary>
        public static string UnreadBadgeAriaLabel {
            get {
                return ResourceManager.GetString("UnreadBadgeAriaLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No notifications yet..
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mark all read.
        /// </summary>
        public static string MarkAllRead {
            get {
                return ResourceManager.GetString("MarkAllRead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mark read.
        /// </summary>
        public static string MarkRead {
            get {
                return ResourceManager.GetString("MarkRead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View all.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string ColMessage {
            get {
                return ResourceManager.GetString("ColMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        public static string ColCreated {
            get {
                return ResourceManager.GetString("ColCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ColStatus {
            get {
                return ResourceManager.GetString("ColStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string ColActions {
            get {
                return ResourceManager.GetString("ColActions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to now.
        /// </summary>
        public static string TimeJustNow {
            get {
                return ResourceManager.GetString("TimeJustNow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}m.
        /// </summary>
        public static string TimeMinutesFormat {
            get {
                return ResourceManager.GetString("TimeMinutesFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}h.
        /// </summary>
        public static string TimeHoursFormat {
            get {
                return ResourceManager.GetString("TimeHoursFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}d.
        /// </summary>
        public static string TimeDaysFormat {
            get {
                return ResourceManager.GetString("TimeDaysFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string StatusRead {
            get {
                return ResourceManager.GetString("StatusRead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unread.
        /// </summary>
        public static string StatusUnread {
            get {
                return ResourceManager.GetString("StatusUnread", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} sent you a message.
        /// </summary>
        public static string ChatMessageReceived {
            get {
                return ResourceManager.GetString("ChatMessageReceived", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your certificate for "{0}" is ready.
        /// </summary>
        public static string CertificateIssued {
            get {
                return ResourceManager.GetString("CertificateIssued", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your subscription to {0} is now active.
        /// </summary>
        public static string SubscriptionActivated {
            get {
                return ResourceManager.GetString("SubscriptionActivated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your subscription expires soon.
        /// </summary>
        public static string SubscriptionExpiring {
            get {
                return ResourceManager.GetString("SubscriptionExpiring", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your {0} subscription has expired — you&apos;re now on the Free plan.
        /// </summary>
        public static string SubscriptionExpired {
            get {
                return ResourceManager.GetString("SubscriptionExpired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your review for "{0}" was approved.
        /// </summary>
        public static string ReviewApproved {
            get {
                return ResourceManager.GetString("ReviewApproved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "{0}" starts in 15 minutes.
        /// </summary>
        public static string SessionReminder {
            get {
                return ResourceManager.GetString("SessionReminder", resourceCulture);
            }
        }
    }
}
