//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResetYourFuture.Shared.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PathRes {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PathRes() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResetYourFuture.Shared.Resources.PathRes", typeof(PathRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string PathsTitle {
            get { return ResourceManager.GetString("PathsTitle", resourceCulture); }
        }

        public static string NoPathsYet {
            get { return ResourceManager.GetString("NoPathsYet", resourceCulture); }
        }

        public static string StepsCountFormat {
            get { return ResourceManager.GetString("StepsCountFormat", resourceCulture); }
        }

        public static string ProgressFormat {
            get { return ResourceManager.GetString("ProgressFormat", resourceCulture); }
        }

        public static string ViewPath {
            get { return ResourceManager.GetString("ViewPath", resourceCulture); }
        }

        public static string BackToPaths {
            get { return ResourceManager.GetString("BackToPaths", resourceCulture); }
        }

        public static string StepLocked {
            get { return ResourceManager.GetString("StepLocked", resourceCulture); }
        }

        public static string StepNext {
            get { return ResourceManager.GetString("StepNext", resourceCulture); }
        }

        public static string StepCompleted {
            get { return ResourceManager.GetString("StepCompleted", resourceCulture); }
        }

        public static string GoToCourse {
            get { return ResourceManager.GetString("GoToCourse", resourceCulture); }
        }

        public static string SignInToTrackProgress {
            get { return ResourceManager.GetString("SignInToTrackProgress", resourceCulture); }
        }

        public static string Loading {
            get { return ResourceManager.GetString("Loading", resourceCulture); }
        }

        public static string PathNotFound {
            get { return ResourceManager.GetString("PathNotFound", resourceCulture); }
        }

        public static string AdminPageTitle {
            get { return ResourceManager.GetString("AdminPageTitle", resourceCulture); }
        }

        public static string NewPath {
            get { return ResourceManager.GetString("NewPath", resourceCulture); }
        }

        public static string EditPath {
            get { return ResourceManager.GetString("EditPath", resourceCulture); }
        }

        public static string NoPathsFound {
            get { return ResourceManager.GetString("NoPathsFound", resourceCulture); }
        }

        public static string ColTitle {
            get { return ResourceManager.GetString("ColTitle", resourceCulture); }
        }

        public static string ColCategory {
            get { return ResourceManager.GetString("ColCategory", resourceCulture); }
        }

        public static string ColSteps {
            get { return ResourceManager.GetString("ColSteps", resourceCulture); }
        }

        public static string ColOrder {
            get { return ResourceManager.GetString("ColOrder", resourceCulture); }
        }

        public static string ColStatus {
            get { return ResourceManager.GetString("ColStatus", resourceCulture); }
        }

        public static string ColActions {
            get { return ResourceManager.GetString("ColActions", resourceCulture); }
        }

        public static string StatusDraft {
            get { return ResourceManager.GetString("StatusDraft", resourceCulture); }
        }

        public static string StatusPublished {
            get { return ResourceManager.GetString("StatusPublished", resourceCulture); }
        }

        public static string Edit {
            get { return ResourceManager.GetString("Edit", resourceCulture); }
        }

        public static string Publish {
            get { return ResourceManager.GetString("Publish", resourceCulture); }
        }

        public static string Unpublish {
            get { return ResourceManager.GetString("Unpublish", resourceCulture); }
        }

        public static string Delete {
            get { return ResourceManager.GetString("Delete", resourceCulture); }
        }

        public static string ConfirmDelete {
            get { return ResourceManager.GetString("ConfirmDelete", resourceCulture); }
        }

        public static string Cancel {
            get { return ResourceManager.GetString("Cancel", resourceCulture); }
        }

        public static string Save {
            get { return ResourceManager.GetString("Save", resourceCulture); }
        }

        public static string FieldTitleEn {
            get { return ResourceManager.GetString("FieldTitleEn", resourceCulture); }
        }

        public static string FieldTitleEl {
            get { return ResourceManager.GetString("FieldTitleEl", resourceCulture); }
        }

        public static string FieldDescriptionEn {
            get { return ResourceManager.GetString("FieldDescriptionEn", resourceCulture); }
        }

        public static string FieldDescriptionEl {
            get { return ResourceManager.GetString("FieldDescriptionEl", resourceCulture); }
        }

        public static string FieldCategory {
            get { return ResourceManager.GetString("FieldCategory", resourceCulture); }
        }

        public static string NoCategory {
            get { return ResourceManager.GetString("NoCategory", resourceCulture); }
        }

        public static string FieldDisplayOrder {
            get { return ResourceManager.GetString("FieldDisplayOrder", resourceCulture); }
        }

        public static string StepsSectionTitle {
            get { return ResourceManager.GetString("StepsSectionTitle", resourceCulture); }
        }

        public static string NoStepsYet {
            get { return ResourceManager.GetString("NoStepsYet", resourceCulture); }
        }

        public static string AddStepsHint {
            get { return ResourceManager.GetString("AddStepsHint", resourceCulture); }
        }

        public static string AddStep {
            get { return ResourceManager.GetString("AddStep", resourceCulture); }
        }

        public static string SelectCourse {
            get { return ResourceManager.GetString("SelectCourse", resourceCulture); }
        }

        public static string MoveUp {
            get { return ResourceManager.GetString("MoveUp", resourceCulture); }
        }

        public static string MoveDown {
            get { return ResourceManager.GetString("MoveDown", resourceCulture); }
        }

        public static string Remove {
            get { return ResourceManager.GetString("Remove", resourceCulture); }
        }

        public static string SaveError {
            get { return ResourceManager.GetString("SaveError", resourceCulture); }
        }
    }
}
