//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResetYourFuture.Shared.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReviewRes {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReviewRes() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResetYourFuture.Shared.Resources.ReviewRes", typeof(ReviewRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string ReviewsTitle {
            get { return ResourceManager.GetString("ReviewsTitle", resourceCulture); }
        }

        public static string NoReviewsYet {
            get { return ResourceManager.GetString("NoReviewsYet", resourceCulture); }
        }

        public static string RatingSummaryFormat {
            get { return ResourceManager.GetString("RatingSummaryFormat", resourceCulture); }
        }

        public static string WriteReview {
            get { return ResourceManager.GetString("WriteReview", resourceCulture); }
        }

        public static string EditReview {
            get { return ResourceManager.GetString("EditReview", resourceCulture); }
        }

        public static string RatingLabel {
            get { return ResourceManager.GetString("RatingLabel", resourceCulture); }
        }

        public static string BodyLabel {
            get { return ResourceManager.GetString("BodyLabel", resourceCulture); }
        }

        public static string BodyPlaceholder {
            get { return ResourceManager.GetString("BodyPlaceholder", resourceCulture); }
        }

        public static string SubmitReview {
            get { return ResourceManager.GetString("SubmitReview", resourceCulture); }
        }

        public static string UpdateReview {
            get { return ResourceManager.GetString("UpdateReview", resourceCulture); }
        }

        public static string Cancel {
            get { return ResourceManager.GetString("Cancel", resourceCulture); }
        }

        public static string EnrollToReview {
            get { return ResourceManager.GetString("EnrollToReview", resourceCulture); }
        }

        public static string MyReviewPending {
            get { return ResourceManager.GetString("MyReviewPending", resourceCulture); }
        }

        public static string MyReviewRejected {
            get { return ResourceManager.GetString("MyReviewRejected", resourceCulture); }
        }

        public static string SubmitError {
            get { return ResourceManager.GetString("SubmitError", resourceCulture); }
        }

        public static string AdminPageTitle {
            get { return ResourceManager.GetString("AdminPageTitle", resourceCulture); }
        }

        public static string ColCourse {
            get { return ResourceManager.GetString("ColCourse", resourceCulture); }
        }

        public static string ColAuthor {
            get { return ResourceManager.GetString("ColAuthor", resourceCulture); }
        }

        public static string ColRating {
            get { return ResourceManager.GetString("ColRating", resourceCulture); }
        }

        public static string ColReview {
            get { return ResourceManager.GetString("ColReview", resourceCulture); }
        }

        public static string ColStatus {
            get { return ResourceManager.GetString("ColStatus", resourceCulture); }
        }

        public static string ColCreated {
            get { return ResourceManager.GetString("ColCreated", resourceCulture); }
        }

        public static string ColActions {
            get { return ResourceManager.GetString("ColActions", resourceCulture); }
        }

        public static string Approve {
            get { return ResourceManager.GetString("Approve", resourceCulture); }
        }

        public static string Reject {
            get { return ResourceManager.GetString("Reject", resourceCulture); }
        }

        public static string StatusPending {
            get { return ResourceManager.GetString("StatusPending", resourceCulture); }
        }

        public static string StatusApproved {
            get { return ResourceManager.GetString("StatusApproved", resourceCulture); }
        }

        public static string StatusRejected {
            get { return ResourceManager.GetString("StatusRejected", resourceCulture); }
        }

        public static string FilterAll {
            get { return ResourceManager.GetString("FilterAll", resourceCulture); }
        }

        public static string NoReviewsToModerate {
            get { return ResourceManager.GetString("NoReviewsToModerate", resourceCulture); }
        }

        public static string Loading {
            get { return ResourceManager.GetString("Loading", resourceCulture); }
        }
    }
}
