//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResetYourFuture.Shared.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SearchRes {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SearchRes() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResetYourFuture.Shared.Resources.SearchRes", typeof(SearchRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search courses, assessments, articles….
        /// </summary>
        public static string Placeholder {
            get {
                return ResourceManager.GetString("Placeholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No results found..
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to See all results.
        /// </summary>
        public static string SeeAllResults {
            get {
                return ResourceManager.GetString("SeeAllResults", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Showing title matches — smart search is temporarily unavailable..
        /// </summary>
        public static string FallbackNotice {
            get {
                return ResourceManager.GetString("FallbackNotice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Results for "{0}".
        /// </summary>
        public static string ResultsForFormat {
            get {
                return ResourceManager.GetString("ResultsForFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string TypeCourse {
            get {
                return ResourceManager.GetString("TypeCourse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Assessment.
        /// </summary>
        public static string TypeAssessment {
            get {
                return ResourceManager.GetString("TypeAssessment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string TypeBlogArticle {
            get {
                return ResourceManager.GetString("TypeBlogArticle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type to search the site..
        /// </summary>
        public static string EnterQuery {
            get {
                return ResourceManager.GetString("EnterQuery", resourceCulture);
            }
        }
    }
}
