//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResetYourFuture.Shared.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SessionRes {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SessionRes() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResetYourFuture.Shared.Resources.SessionRes", typeof(SessionRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string PageTitle {
            get { return ResourceManager.GetString("PageTitle", resourceCulture); }
        }

        public static string Loading {
            get { return ResourceManager.GetString("Loading", resourceCulture); }
        }

        public static string NoUpcomingSessions {
            get { return ResourceManager.GetString("NoUpcomingSessions", resourceCulture); }
        }

        public static string StatusScheduled {
            get { return ResourceManager.GetString("StatusScheduled", resourceCulture); }
        }

        public static string StatusLive {
            get { return ResourceManager.GetString("StatusLive", resourceCulture); }
        }

        public static string StatusEnded {
            get { return ResourceManager.GetString("StatusEnded", resourceCulture); }
        }

        public static string StatusCancelled {
            get { return ResourceManager.GetString("StatusCancelled", resourceCulture); }
        }

        public static string HostedByFormat {
            get { return ResourceManager.GetString("HostedByFormat", resourceCulture); }
        }

        public static string DurationFormat {
            get { return ResourceManager.GetString("DurationFormat", resourceCulture); }
        }

        public static string ParticipantsFormat {
            get { return ResourceManager.GetString("ParticipantsFormat", resourceCulture); }
        }

        public static string CallInProgress {
            get { return ResourceManager.GetString("CallInProgress", resourceCulture); }
        }

        public static string StartSession {
            get { return ResourceManager.GetString("StartSession", resourceCulture); }
        }

        public static string JoinSession {
            get { return ResourceManager.GetString("JoinSession", resourceCulture); }
        }

        public static string Registered {
            get { return ResourceManager.GetString("Registered", resourceCulture); }
        }

        public static string Unregister {
            get { return ResourceManager.GetString("Unregister", resourceCulture); }
        }

        public static string Full {
            get { return ResourceManager.GetString("Full", resourceCulture); }
        }

        public static string Register {
            get { return ResourceManager.GetString("Register", resourceCulture); }
        }

        public static string RegisterError {
            get { return ResourceManager.GetString("RegisterError", resourceCulture); }
        }

        public static string JoinError {
            get { return ResourceManager.GetString("JoinError", resourceCulture); }
        }

        public static string AdminPageTitle {
            get { return ResourceManager.GetString("AdminPageTitle", resourceCulture); }
        }

        public static string NewSession {
            get { return ResourceManager.GetString("NewSession", resourceCulture); }
        }

        public static string EditSession {
            get { return ResourceManager.GetString("EditSession", resourceCulture); }
        }

        public static string NoSessionsFound {
            get { return ResourceManager.GetString("NoSessionsFound", resourceCulture); }
        }

        public static string ColTitle {
            get { return ResourceManager.GetString("ColTitle", resourceCulture); }
        }

        public static string ColHost {
            get { return ResourceManager.GetString("ColHost", resourceCulture); }
        }

        public static string ColCourse {
            get { return ResourceManager.GetString("ColCourse", resourceCulture); }
        }

        public static string ColWhen {
            get { return ResourceManager.GetString("ColWhen", resourceCulture); }
        }

        public static string ColParticipants {
            get { return ResourceManager.GetString("ColParticipants", resourceCulture); }
        }

        public static string ColStatus {
            get { return ResourceManager.GetString("ColStatus", resourceCulture); }
        }

        public static string ColActions {
            get { return ResourceManager.GetString("ColActions", resourceCulture); }
        }

        public static string Edit {
            get { return ResourceManager.GetString("Edit", resourceCulture); }
        }

        public static string CancelSession {
            get { return ResourceManager.GetString("CancelSession", resourceCulture); }
        }

        public static string FieldTitleEn {
            get { return ResourceManager.GetString("FieldTitleEn", resourceCulture); }
        }

        public static string FieldTitleEl {
            get { return ResourceManager.GetString("FieldTitleEl", resourceCulture); }
        }

        public static string FieldCourse {
            get { return ResourceManager.GetString("FieldCourse", resourceCulture); }
        }

        public static string NoCourse {
            get { return ResourceManager.GetString("NoCourse", resourceCulture); }
        }

        public static string FieldStartsAt {
            get { return ResourceManager.GetString("FieldStartsAt", resourceCulture); }
        }

        public static string FieldDuration {
            get { return ResourceManager.GetString("FieldDuration", resourceCulture); }
        }

        public static string FieldMaxParticipants {
            get { return ResourceManager.GetString("FieldMaxParticipants", resourceCulture); }
        }

        public static string Save {
            get { return ResourceManager.GetString("Save", resourceCulture); }
        }

        public static string Cancel {
            get { return ResourceManager.GetString("Cancel", resourceCulture); }
        }

        public static string SaveError {
            get { return ResourceManager.GetString("SaveError", resourceCulture); }
        }

        public static string CancelConfirmFormat {
            get { return ResourceManager.GetString("CancelConfirmFormat", resourceCulture); }
        }
    }
}
