//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResetYourFuture.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SubscriptionSuccessRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubscriptionSuccessRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResetYourFuture.Shared.Resources.SubscriptionSuccessRes", typeof(SubscriptionSuccessRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Pricing.
        /// </summary>
        public static string BtnBackToPricing {
            get {
                return ResourceManager.GetString("BtnBackToPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Courses.
        /// </summary>
        public static string BtnBrowseCourses {
            get {
                return ResourceManager.GetString("BtnBrowseCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Plans.
        /// </summary>
        public static string BtnViewPlans {
            get {
                return ResourceManager.GetString("BtnViewPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan:.
        /// </summary>
        public static string LabelPlan {
            get {
                return ResourceManager.GetString("LabelPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renews:.
        /// </summary>
        public static string LabelRenews {
            get {
                return ResourceManager.GetString("LabelRenews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started:.
        /// </summary>
        public static string LabelStarted {
            get {
                return ResourceManager.GetString("LabelStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading your subscription....
        /// </summary>
        public static string LoadingSubscription {
            get {
                return ResourceManager.GetString("LoadingSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Updated - Reset Your Future.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re on the {0} plan!.
        /// </summary>
        public static string PlanHeadingFormat {
            get {
                return ResourceManager.GetString("PlanHeadingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your subscription is now active. Enjoy your new features..
        /// </summary>
        public static string SubscriptionActive {
            get {
                return ResourceManager.GetString("SubscriptionActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load subscription details..
        /// </summary>
        public static string UnableToLoad {
            get {
                return ResourceManager.GetString("UnableToLoad", resourceCulture);
            }
        }
    }
}
