//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResetYourFuture.Shared.Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessagesRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessagesRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResetYourFuture.Shared.Resources.Messages.ErrorMessagesRes", typeof(ErrorMessagesRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Confirming Email.
        /// </summary>
        public static string EmailConfirmationError {
            get {
                return ResourceManager.GetString("EmailConfirmationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is already registered. Please use a different email or try logging in..
        /// </summary>
        public static string EmailTakenError {
            get {
                return ResourceManager.GetString("EmailTakenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Error.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account Disabled.
        /// </summary>
        public static string AccountDisabled {
            get {
                return ResourceManager.GetString("AccountDisabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your account has been disabled by an administrator.
        /// </summary>
        public static string AccountDisabledMessage {
            get {
                return ResourceManager.GetString("AccountDisabledMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to If you believe this is a mistake, please contact support for assistance.
        /// </summary>
        public static string AccountDisabledContact {
            get {
                return ResourceManager.GetString("AccountDisabledContact", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Back to Login.
        /// </summary>
        public static string BackToLogin {
            get {
                return ResourceManager.GetString("BackToLogin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your email address isn't confirmed yet. Please check your inbox for the confirmation link..
        /// </summary>
        public static string EmailNotConfirmedHint {
            get {
                return ResourceManager.GetString("EmailNotConfirmedHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials..
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email not confirmed..
        /// </summary>
        public static string EmailNotConfirmedError {
            get {
                return ResourceManager.GetString("EmailNotConfirmedError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your account has been disabled. Please contact support..
        /// </summary>
        public static string AccountDisabledContactSupport {
            get {
                return ResourceManager.GetString("AccountDisabledContactSupport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account locked. Try again later..
        /// </summary>
        public static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid or expired refresh token..
        /// </summary>
        public static string InvalidOrExpiredRefreshToken {
            get {
                return ResourceManager.GetString("InvalidOrExpiredRefreshToken", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account is disabled..
        /// </summary>
        public static string AccountIsDisabled {
            get {
                return ResourceManager.GetString("AccountIsDisabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid request..
        /// </summary>
        public static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registration failed. Please check your details and try again..
        /// </summary>
        public static string RegistrationFailedGeneric {
            get {
                return ResourceManager.GetString("RegistrationFailedGeneric", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid confirmation link..
        /// </summary>
        public static string InvalidConfirmationLink {
            get {
                return ResourceManager.GetString("InvalidConfirmationLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Assessment access requires a Plus subscription or higher..
        /// </summary>
        public static string AssessmentAccessRequiresPlus {
            get {
                return ResourceManager.GetString("AssessmentAccessRequiresPlus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your answers don't match this assessment's questions..
        /// </summary>
        public static string AssessmentAnswersInvalid {
            get {
                return ResourceManager.GetString("AssessmentAnswersInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Assessment not found or not published.
        /// </summary>
        public static string AssessmentNotFoundOrUnpublished {
            get {
                return ResourceManager.GetString("AssessmentNotFoundOrUnpublished", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This assessment requires a {0} subscription or higher..
        /// </summary>
        public static string AssessmentRequiresTierFormat {
            get {
                return ResourceManager.GetString("AssessmentRequiresTierFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Course not found.
        /// </summary>
        public static string CourseNotFound {
            get {
                return ResourceManager.GetString("CourseNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This course requires a {0} subscription or higher. Please upgrade your plan..
        /// </summary>
        public static string CourseRequiresTierFormat {
            get {
                return ResourceManager.GetString("CourseRequiresTierFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your {0} plan allows up to {1} course(s). Please upgrade to enroll in more courses..
        /// </summary>
        public static string CourseEnrollmentLimitReachedFormat {
            get {
                return ResourceManager.GetString("CourseEnrollmentLimitReachedFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lesson not found.
        /// </summary>
        public static string LessonNotFound {
            get {
                return ResourceManager.GetString("LessonNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You must be enrolled in this course to view lessons.
        /// </summary>
        public static string MustBeEnrolledToViewLessons {
            get {
                return ResourceManager.GetString("MustBeEnrolledToViewLessons", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not enrolled in this course.
        /// </summary>
        public static string NotEnrolledInCourse {
            get {
                return ResourceManager.GetString("NotEnrolledInCourse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No file provided.
        /// </summary>
        public static string NoFileProvided {
            get {
                return ResourceManager.GetString("NoFileProvided", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File too large (max 5 MB).
        /// </summary>
        public static string FileTooLarge5Mb {
            get {
                return ResourceManager.GetString("FileTooLarge5Mb", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Only image files are allowed (jpeg, png, gif, webp)..
        /// </summary>
        public static string OnlyImageFilesAllowed {
            get {
                return ResourceManager.GetString("OnlyImageFilesAllowed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to save avatar..
        /// </summary>
        public static string FailedToSaveAvatar {
            get {
                return ResourceManager.GetString("FailedToSaveAvatar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A category with this name already exists..
        /// </summary>
        public static string CategoryNameExists {
            get {
                return ResourceManager.GetString("CategoryNameExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Category not found.
        /// </summary>
        public static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. Please try again..
        /// </summary>
        public static string UnexpectedErrorTryAgain {
            get {
                return ResourceManager.GetString("UnexpectedErrorTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the server. Please try again..
        /// </summary>
        public static string UnableToConnect {
            get {
                return ResourceManager.GetString("UnableToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email and new password..
        /// </summary>
        public static string EnterEmailAndPassword {
            get {
                return ResourceManager.GetString("EnterEmailAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error resetting password..
        /// </summary>
        public static string PasswordResetFailed {
            get {
                return ResourceManager.GetString("PasswordResetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load billing information. Please try again..
        /// </summary>
        public static string FailedToLoadBilling {
            get {
                return ResourceManager.GetString("FailedToLoadBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to cancel. Please try again..
        /// </summary>
        public static string FailedToCancel {
            get {
                return ResourceManager.GetString("FailedToCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load courses. Please try again..
        /// </summary>
        public static string FailedToLoadCourses {
            get {
                return ResourceManager.GetString("FailedToLoadCourses", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to load analytics. Please try again..
        /// </summary>
        public static string FailedToLoadAnalytics {
            get {
                return ResourceManager.GetString("FailedToLoadAnalytics", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to load course. Please try again..
        /// </summary>
        public static string FailedToLoadCourse {
            get {
                return ResourceManager.GetString("FailedToLoadCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to enroll. Please try again..
        /// </summary>
        public static string FailedToEnroll {
            get {
                return ResourceManager.GetString("FailedToEnroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending reset link..
        /// </summary>
        public static string FailedToSendResetLink {
            get {
                return ResourceManager.GetString("FailedToSendResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied..
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string Auth_EmailRequired {
            get {
                return ResourceManager.GetString("Auth_EmailRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter a valid email address..
        /// </summary>
        public static string Auth_EmailInvalid {
            get {
                return ResourceManager.GetString("Auth_EmailInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string Auth_PasswordRequired {
            get {
                return ResourceManager.GetString("Auth_PasswordRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters and include an uppercase letter and a digit..
        /// </summary>
        public static string Auth_PasswordComplexity {
            get {
                return ResourceManager.GetString("Auth_PasswordComplexity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please confirm your password..
        /// </summary>
        public static string Auth_ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("Auth_ConfirmPasswordRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string Auth_PasswordMismatch {
            get {
                return ResourceManager.GetString("Auth_PasswordMismatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First name is required..
        /// </summary>
        public static string Auth_FirstNameRequired {
            get {
                return ResourceManager.GetString("Auth_FirstNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Last name is required..
        /// </summary>
        public static string Auth_LastNameRequired {
            get {
                return ResourceManager.GetString("Auth_LastNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You must consent to data processing..
        /// </summary>
        public static string Auth_GdprConsentRequired {
            get {
                return ResourceManager.GetString("Auth_GdprConsentRequired", resourceCulture);
            }
        }

    }
}
