//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResetYourFuture.Shared.Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SuccessMessagesRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuccessMessagesRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResetYourFuture.Shared.Resources.Messages.SuccessMessagesRes", typeof(SuccessMessagesRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirmed.
        /// </summary>
        public static string EmailConfirmationSuccess {
            get {
                return ResourceManager.GetString("EmailConfirmationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Successful ! , please check your email.
        /// </summary>
        public static string RegistrationSuccess {
            get {
                return ResourceManager.GetString("RegistrationSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registration successful. Please confirm your email..
        /// </summary>
        public static string RegistrationSuccessfulNoEmail {
            get {
                return ResourceManager.GetString("RegistrationSuccessfulNoEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registration successful. Please check your email to confirm your account..
        /// </summary>
        public static string RegistrationSuccessfulCheckEmail {
            get {
                return ResourceManager.GetString("RegistrationSuccessfulCheckEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email confirmed successfully..
        /// </summary>
        public static string EmailConfirmedSuccessfully {
            get {
                return ResourceManager.GetString("EmailConfirmedSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to If the email exists, a reset link has been sent..
        /// </summary>
        public static string PasswordResetLinkSent {
            get {
                return ResourceManager.GetString("PasswordResetLinkSent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password reset successfully..
        /// </summary>
        public static string PasswordResetSuccessful {
            get {
                return ResourceManager.GetString("PasswordResetSuccessful", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enrolled successfully.
        /// </summary>
        public static string EnrolledSuccessfully {
            get {
                return ResourceManager.GetString("EnrolledSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Already enrolled.
        /// </summary>
        public static string AlreadyEnrolled {
            get {
                return ResourceManager.GetString("AlreadyEnrolled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lesson completed.
        /// </summary>
        public static string LessonCompletedMsg {
            get {
                return ResourceManager.GetString("LessonCompletedMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Already completed.
        /// </summary>
        public static string AlreadyCompleted {
            get {
                return ResourceManager.GetString("AlreadyCompleted", resourceCulture);
            }
        }
    }
}
